### PR TITLE
Allow undefined in the first position of callbacks

### LINKED ISSUE #21: Expected "null" instead of "undefined" in error position of callback
After upgrading to the below versions of the respective packages I started to get the above error for the following code:

```(javascript)
callback(undefined, {
  statusCode: 200,
  body: JSON.stringify(data)
})
```

However, the rule descriptions states, that `undefined` should be valid? Can someone explain, why I get this error?

**Versions**:
eslint: 4.2.0
eslint-config-standard: 10.2.1
eslint-plugin-standard: 3.0.1

### PR DESCRIPTION
**Pull request by delaguilaluis**
Fixes #21.

### CODE REVIEW

**Comment by xjamundx** [comment]
I'm 👍 on this

**Comment by feross** [comment]
I actually prefer `undefined` to represent the un-set, default value for "nothing". And `null` to represent an explicit, user-set "nothing".

Pretty sure we intentionally excluded `undefined` when making this rule.

What's the reasoning for allowing `undefined`?

**Comment by delaguilaluis** [comment]
Interesting way to see it. Thank you.

Lately I tried to stick with only _one way_ to represent the absence of value (`undefined`), so I bumped with this rule, and, after looking at the README, the rule description deferred from the behaviour:

>- `no-callback-literal` - Ensures that we strictly follow the callback pattern with `undefined`, `null` or an error object in the first position of a callback.

That's the only reason for the change, and if this is a _breaking change_ we don't want to ship, then maybe we should revert it and just update the READM instead.

**Comment by feross** [comment]
@delaguilaluis Thanks for pointing out the inconsistency with the documentation. I'm curious what @xjamundx's opinion is on this stylistic issue. Let's wait to hear from him before publishing a new version or reverting.

**Comment by xjamundx** [comment]
Yeah hey I'm pretty out of touch on this stuff, but here's my 2 cents:

1. The callback pattern has historically been `callback(null, data)`
2. Since ES6 (especially with optional arguments) there has been a trend to use `undefined` as the one true empty value in JS

I don't see any special value in using `undefined` for the callback pattern, however, supporting this for folks that want to use `undefined` everywhere seems fine to me. 👍

**Comment by feross** [comment]
Fair enough :

**Comment by feross** [comment]
Released as 3.1.0 ✨

**Pull request merged**
